In [ ]:
# Importando o pytorch
import torch

<div align="justify">
<b>TENSOR:</b> É uma lista multidimensional de valores numéricos. Quando apenas é unidimensional, ou seja, apenas um eixo é necessário, um tensor é chamado de <b>vetor</b>. Já quando ele tem duas dimensões, é chamado de <b>matriz</b>. Para mais de duas dimensões (K > 2), o tensor é apenas chamado de <b>tensor de ordem K</b>.
</div>
<br>
<div align="justify">
Um <b>tensor</b> pode ser criado de várias formas pré-setadas pelo pytorch. Por exemplo, usar o <b>torch.arange(n)</b> te permite criar um vetor (tensor unidimensional) com valores igualmente espaçados, começando no <b>0</b> e terminando em <b>"n"</b>. O padrão é um intervalo de tamanho 1, mas dá pra especificar diferentes intervalos.
</div>
<br>
<div align="justify">
<b>OBS.:</b> Se você não falar nada, ele vai usar o CPU para rodar... é bom sempre especificar o GPU, por motivos de melhor processamento paralelo.
</div>

In [28]:
print("="*20)
print("Criando um tensor 1D:")
x = torch.arange(12, dtype=torch.float32)
print(x)
print("="*20)
print("O tensor x é um vetor unidimensional com 12 elementos.")
print("Número de elementos:", x.numel())
print("O shape do tensor é o tamanho para cada dimensão (eixo):")
print(x.shape)
print("="*20)
print("Usando view para ver esse tensor em diferentes formatos:")
print("Vendo x (1D, shape = 12) como ficaria numa matriz (2D, shape = 6,2):")
print(x.view(6, 2))
print("="*20)
print("Vendo o mesmo x (1D, shape = 12) como ficaria numa matriz (2D, shape = 4,3):")
print(x.view(4, 3))
print("="*20)
print("Usando reshape para realmente modificar o shape de x:")
# Criando um tensor 3x4
x = x.reshape(3, 4)
print(x)
print("="*20)

Criando um tensor 1D:
tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
O tensor x é um vetor unidimensional com 12 elementos.
Número de elementos: 12
O shape do tensor é o tamanho para cada dimensão (eixo):
torch.Size([12])
Usando view para ver esse tensor em diferentes formatos:
Vendo x (1D, shape = 12) como ficaria numa matriz (2D, shape = 6,2):
tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]])
Vendo o mesmo x (1D, shape = 12) como ficaria numa matriz (2D, shape = 4,3):
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
Usando reshape para realmente modificar o shape de x:
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


<div align="justify">
O python segue uma ordem row-major... ou seja, para matrizes, você tem algo da seguinte lógica:
</div>
<br>
[
<br>
[ 0,  1,  2,  3],    ← 1ª linha
<br>
 [ 4,  5,  6,  7],   ← 2ª linha
 <br>
 [ 8,  9, 10, 11]    ← 3ª linha
 <br>
]
<br>

<br>

| Índice (`x[i]`) | Valor | Posição em `X` |
|----------------|--------|----------------|
| `x[0]`         | `0`      | `X[0, 0]`       |
| `x[1]`         | `1`      | `X[0, 1]`       |
| `x[2]`         | `2`      | `X[0, 2]`       |
| `x[3]`         | `3`      | `X[0, 3]`       |
| `x[4]`         | `4`      | `X[1, 0]`       |
| `x[5]`         | `5`      | `X[1, 1]`       |

<br>


<div align="justify">
Isso significa que ele percorre primeiro as linhas para depois percorrer as colunas. Após percorrer os índices da 1ª linha, de 0 a 3, o índice 4 será o primeiro valor da segunda linha, que será também percorrida até o final antes de mudar para a 3ª linha.
</div>

<br>
<div align="justify">
Você pode usar um <b>-1</b> no <b>x.reshape()</b> para inferir o size que falta...por exemplo, <b>sabemos que o shape é 12</b>, e que <b>uma das dimensões é 3</b>, podemos usar o <b>x.reshape(3,-1)</b> para receber o mesmo que fazer <b>x.reshape(3,4)</b>. O mesmo vale se soubessemos que <b>uma das dimensões é 4, mas não que a outra é 3</b>... usaríamos <b>x.reshape(-1,4)</b> para conseguir o mesmo que fazer <b>x.reshape(3,4)</b>.
</div>
<br>

In [ ]:
print("Vendo outras dimensões de reshape:")
print("3D:")
print(x.reshape(2, 3, 2))
print("="*20)


Vendo outras dimensões de reshape:
3D:
tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.]],

        [[ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]]])
4D:
tensor([[[[ 0.],
          [ 1.]],

         [[ 2.],
          [ 3.]],

         [[ 4.],
          [ 5.]]],


        [[[ 6.],
          [ 7.]],

         [[ 8.],
          [ 9.]],

         [[10.],
          [11.]]]])
Vendo um reshape para 5D:
5D:
tensor([[[[[ 0.]],

          [[ 1.]]],


         [[[ 2.]],

          [[ 3.]]],


         [[[ 4.]],

          [[ 5.]]]],



        [[[[ 6.]],

          [[ 7.]]],


         [[[ 8.]],

          [[ 9.]]],


         [[[10.]],

          [[11.]]]]])


In [37]:

print("4D:")
print(x.reshape(2, 3, 2, 1))
print("="*20)

4D:
tensor([[[[ 0.],
          [ 1.]],

         [[ 2.],
          [ 3.]],

         [[ 4.],
          [ 5.]]],


        [[[ 6.],
          [ 7.]],

         [[ 8.],
          [ 9.]],

         [[10.],
          [11.]]]])


In [38]:

print("Vendo um reshape para 5D:")
print("5D:")
print(x.reshape(2, 3, 2, 1, 1))
print("="*20)

Vendo um reshape para 5D:
5D:
tensor([[[[[ 0.]],

          [[ 1.]]],


         [[[ 2.]],

          [[ 3.]]],


         [[[ 4.]],

          [[ 5.]]]],



        [[[[ 6.]],

          [[ 7.]]],


         [[[ 8.]],

          [[ 9.]]],


         [[[10.]],

          [[11.]]]]])


In [39]:

print("="*20)
# print(y.numel())
# print(y.shape)
z = torch.zeros((2,3,4))
print("Tensor 3D, preenchido apenas com zeros:")
print(z)
print("="*20)
z2 = torch.ones((3,3,4))
print("Tensor 3D, preenchido apenas com uns:")
print(z2)
print("="*20)

Tensor 3D, preenchido apenas com zeros:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Tensor 3D, preenchido apenas com uns:
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


<div align="justify">
Para gerar um tensor com valores aleatórios (distribuição Normal Padrão):
</div>
<br>

<div align="justify">
Usar: <b>torch.randn(i,j)</b>
</div>
<br>


<div align="justify">
Para gerar um tensor com valores aleatórios entre 0 e 1 (distribuição Uniforme):
</div>
<br>

<div align="justify">
Usar: <b>torch.rand(i,j)</b>
</div>
<br>

<div align="justify">
Para gerar um tensor com valores inteiros aleatórios:
</div>
<br>

<div align="justify">
Usar: <b>torch.randint(low=0, high=n, size=(i, j))</b>
</div>
<br>



`Reprodutibilidade (seed):`

<div align="justify">
Faz com que os números aleatórios sempre saiam iguais (útil pra testes/reprodução de resultados).
</div>
<br>


<div align="justify">
Usar: <b>torch.manual_seed(42)</b>
</div>
<br>


### 📊 Distribuições de probabilidade no PyTorch

| Distribuição             | Código PyTorch                                                                 | Observações                         |
|--------------------------|--------------------------------------------------------------------------------|-------------------------------------|
| **Uniforme (0, 1)**      | `torch.rand(3, 4)`                                                             | Valores entre 0 e 1                 |
| **Uniforme (a, b)**      | `torch.empty(3, 4).uniform_(a, b)`                                             | Valores entre `a` e `b`             |
| **Normal padrão (0,1)**  | `torch.randn(3, 4)`                                                            | Média 0, desvio padrão 1            |
| **Normal (μ, σ)**        | `torch.normal(mean=10, std=2, size=(3, 4))`                                    | Média 10, desvio padrão 2           |
| **Inteiros aleatórios**  | `torch.randint(0, 10, (3, 4))`                                                 | Inteiros de 0 a 9                   |
| **Binomial**             | `torch.distributions.Binomial(total_count=10, probs=0.5).sample((3, 4))`       | Nº de sucessos em 10 tentativas     |
| **Poisson**              | `torch.poisson(torch.full((3, 4), 4.0))`                                       | λ = 4 (média esperada)              |
| **Exponencial**          | `torch.distributions.Exponential(rate=1.5).sample((3, 4))`                     | Taxa = 1.5                          |
| **Beta**                 | `torch.distributions.Beta(2.0, 5.0).sample((3, 4))`                             | α = 2, β = 5                        |
| **Gamma**                | `torch.distributions.Gamma(2.0, 2.0).sample((3, 4))`                            | shape = 2.0, scale = 1/2.0          |
| **Multinomial**          | `torch.multinomial(torch.tensor([0.1, 0.3, 0.6]), 5, replacement=True)`         | 5 amostras com reposição           |



In [42]:
print("Tensor 3D, preenchido com números aleatórios (distribuição normal padrão):")
print(torch.randn(3, 4))
print("="*20)
print("Tensor 3D, preenchido com números aleatórios entre 0 e 1 (distribuição uniforme):")
print(torch.rand(3, 4))
print("="*20)
print("E assim por diante...")
print("="*20)


Tensor 3D, preenchido com números aleatórios (distribuição normal padrão):
tensor([[ 2.5824, -2.1266,  0.0952, -0.4975],
        [-0.4141, -0.7074,  0.0068, -1.4450],
        [ 0.4978, -1.3963,  1.2944, -0.6325]])
Tensor 3D, preenchido com números aleatórios entre 0 e 1 (distribuição uniforme):
tensor([[0.4444, 0.9066, 0.3941, 0.2417],
        [0.6981, 0.1906, 0.7665, 0.9007],
        [0.3015, 0.6091, 0.7008, 0.8256]])
E assim por diante...
